services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - API_URL=http://localhost:3001
  #   depends_on:
  #     - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules

volumes:
  pgdata:
