services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
